image: alpine/edge
packages:
  - eudev-dev
  - libinput-dev
  - libseat-dev
  - mesa-dev
  - libffi-dev
  - expat-dev
  - libxkbcommon-dev
  - xcb-util-image-dev
  - xcb-util-renderutil-dev
  - xcb-util-wm-dev
  - pixman-dev
  - libevdev-dev
  - wayland-protocols
  - meson
  - scdoc
  - tar
  - wget
  - xz
sources:
  - https://gitlab.freedesktop.org/wayland/wayland.git
  - https://gitlab.freedesktop.org/wlroots/wlroots.git
  - https://github.com/riverwm/river.git
  - https://git.sr.ht/~novakane/rivercarro
tasks:
  - install_deps: |
      cd wayland
      git checkout 1.21.0
      meson setup build -Ddocumentation=false -Dtests=false --prefix /usr
      sudo ninja -C build install
      cd ..

      cd wlroots
      git checkout 0.16.1
      meson setup build --auto-features=enabled -Drenderers=gles2 -Dexamples=false \
            -Dwerror=false -Db_ndebug=false -Dxwayland=disabled --prefix /usr
      sudo ninja -C build/ install
      cd ..

      wget https://ziglang.org/download/0.10.0/zig-linux-x86_64-0.10.0.tar.xz
      tar -xvf zig-linux-x86_64-0.10.0.tar.xz 1>/dev/null
      sudo mv zig-linux-x86_64-0.10.0/zig /usr/bin/
      sudo mv zig-linux-x86_64-0.10.0/lib /usr/lib/zig

      cd river
      sudo zig build --prefix /usr
  - build: |
      cd rivercarro
      zig build
  - format: |
      cd rivercarro
      zig fmt --check src/
